Feature/passm 14 integrate database
Atharva0418/pwm-backend pull request #6
Opened 2024-09-09 16:50 UTC by Atharva0418

2024-09-09 16:52 UTC, Atharva0418 commented
Check the database integration.  I havent removed the old repository yet, will remove that before merging. Instructions on how to configure this locally is remaining.

2024-09-09 18:47 UTC, chintal31 requested changes

2024-09-09 18:47 UTC, chintal31 commented on src/main/resources/application.properties
It looks like our project would benefit from an improved approach to secret management. Storing sensitive data such as URLs, usernames, and passwords directly in the code or version-controlled configuration files can lead to security vulnerabilities. 

You can review different strategies of loading these sensitive values from external configuration files like .env, or leveraging Spring's profile-based configuration (application.properties or application.yml) for different environments. 

Next Steps: Implement one of these strategies to manage secrets securely, depending on our environment

2024-09-11 21:34 UTC, chintal31 reviewed
Looks good!
Resolve the conflicts, then I'll check it once.

2024-09-12 21:32 UTC, chintal31 approved these changes

2024-09-12 21:33 UTC, merged